# Particle Motion

**Diffusion** fundamentally relies on the fact that the constituents molecules/atoms are constantly undergoing **Fluctuation**.

If I'm interested in the materials properties, I have to understand the motion of the constituent particles and if **there is any kind of correlation** in the motion ($0^{th}$ order).

What other properties are intimately related to the mechanical properties of the material?

- Thermal Properties

## Equilibrium Configuration & Energies

- Statistical Mechanics
- Molecular Thermodynamics

Diffusion: things are moving... they are not really stationary.

The **Dynamics/Response of Fluctuation** must be connected with this **Equilibrium Configuration**. Therefore, we need something else.

Other point to have in mind is **how the mechanical properties behave with and without external forces**:

**External Forces** $\leftrightarrow$ **Configuration**.

**Langevin Equation:**

$m\frac{d\vec{v}}{dt} = -b\vec{v} + \vec{f}(t) + External Forces$

- **Viscous Drag** · Average Property (from average response of solvent - flow): $-b\vec{v}$
- **Rapid Fluctuations** · Instantaneous Property (collisions with solvent molecules): $\vec{f}(t)$
- **External Forces**

**Viscous Drag**

- It is a **Friction Coefficient**

- For a sphere: $b = 6 \pi \eta R$

  - $\eta =$ **Viscosity**
  - $[\eta] = Pa \, s = \frac{N}{m^2} \, s$
  - $[\eta] = \frac{dyne}{cm^2} \, s = Poise$
    
**Newtonian Fluid · A Simple Liquid**

- $\eta = constant$

**Non-Newtonian Fluid · Colloidal or Polymer Solution**

- $\eta \neq constant \rightarrow$ It will depend on **Shear Rate**
    - Milk
    - Shampoo

## Time Scale for Fluid Response

**Assume** $T >> T_g$ (Temperature of Glass Transition)

$t = \frac{LengthScale}{\sqrt{\langle v^2 \rangle}}$

$LengthScale \equiv X \equiv Particle \, Diameter = 2R$

## For Water

It is one molecule of water diffusing in a sea of water molecules:

- $t^* = \frac{DiameterWaterMolecule}{velocity} = \frac{2Angstrons}{velocity} = \frac{0.2 \times 10^{-9}m}{velocity}$

**How do I get the velocity?**

- $\sqrt{\langle (v^*)^2 \rangle} = \frac{k_BT}{m}$

Here we are trying to find the **length scale for a diffusion process**, and we can say that at **R**oom **T**emperature (RT):

$k_{B}T = 4\,pNnm = 4\times10^{-21} Nm \Rightarrow$ **WE NEED TO REMEMBER THIS FOR EXAM**

$t^* = \frac{0.2 \times 10^{-9}m}{\sqrt {4 \times 10^{-21}Nm}} \, \frac{18 \times 10^{-3}\frac{kg}{mole}}{6 \times 10^{23}\frac{molecule}{mole}} = 5 \times 10^{-13} \sim 10^{-12} \, s$

## Modulus

$Modulus \equiv \frac{energy}{volume}$

- $Liquid \sim k_BT$
- $Solid >> k_BT$
- $Gas << k_BT$

Looking only at the **Liquid**:

$Modulus \sim \frac{k_BT}{(2R)^3} \sim \frac{4\times 10^{-21}Nm}{(0.2\times 10^{-9}m)^3} \sim 5\times 10^{8} \frac{N}{m^2} (Pa)$

It tells us that the **viscosity** of any fluid should be of the order of (close to the Boiling Point (BP):

$\eta \sim Modulus \times RelaxationTime = 5 \times 10^{8} \frac{N}{m^2} \, 5\times 10^{-13}s \sim 0.3\times 10^{-3}Pa\,s$

Let's take a step further...
How that is going to impact the evolution of motion:

**Langevin Equation**:

$m\frac{d\vec{v}}{dt} = -b\vec{v} + \vec{f}(t)$

- $\frac{d\vec{v}}{dt} \rightarrow$ is going to **fluctuate** because of $\vec{f}$
- $\vec{f}(t) \rightarrow$ rapidly fluctuate $\sim 10^{-12}s \rightarrow$ due to **collisions** from many solvent motions $\rightarrow$ usually **uncorrelated**.

If there is no correlation between $\vec{f}(t)$ and $\vec{f}(t')$ except at the time equals to $t'$:

- $\langle f(t) \cdot f(t + t') \rangle \propto \delta (t')$

If I'm interested in an average, then:

- $\vec{f}(t) \rightarrow 0$
- $m\frac{d\vec{v}}{dt} = -b\vec{v}$
- **Solution**: $v(t) = v(0) \cdot e^{-\frac{t}{\tau}}$
    - Where $v(0)$ is related to the **boundary/initial condition**
- $\tau \equiv \frac{m}{b} \equiv ViscousRelaxationTimescale$

The only thing we need to worry about is that **if there is a correlation in the motion**... if there is no correlation in the motion, those fluctuations are going to cancel each other out.


## Motions that are Temporarily Correlated

We can now rewrite the **Langevin Equation**:

$\frac{d\vec{v}(t')}{dt'} = -\frac{\vec{v}(t')}{\tau} + \frac{\vec{f}(t')}{m}$

How can I find the velocity for this kind of equation (**solve the differential equation**)?

- Multiply both sides by $e^{\frac{t'}{\tau}}$
- Integrate $\int_{0}^t dt'$
- Integrate by parts: $\int GdF = GF - \int FdG$

If we consider the **average velocity** due to **Fluctuation**:

$\langle \vec{v}(t) \rangle = \langle \vec{v}(0) \rangle e^{-\frac{t}{\tau}} + 0$

($0$ because $\vec{f}$ is random)

**Here is the exercise for the homework:**

When we measure the fluctuations we only measure the motions that are correlated, otherwise they would cancel each other out and be zero.

So, when we are measuring the correlation, we are measuring the **Thermal Energy**:

$\int_{-\infty}^\infty \langle \vec{v}(t) \cdot \vec{v}(0) \rangle dt = \frac{6k_BT}{b}$

- $\frac{6k_BT}{b} \equiv$ **Damping or Dissipation**
- $6 \equiv$ **3 Dimension**
- $b \equiv$ **Drag**

A similar situation is a **current through resistor**:

$\int_{-\infty}^\infty \langle I(t) \cdot I(0) \rangle dt = \frac{6k_BT}{R}$

Diffusion come in for understanding how a given structure evolves as a function of time.

## Classes of problem we are interested in

Continuous Matrix: how does the thing evolves as a function of time?

The obstacles interfere with the velocity of the diffusion:

- Friction
- Viscosity

That's what Langevin equation says:

A particle forgets its velocity over a time of $\tau$.

## MSD

What is the **Mean Square Displacement** due to solvent molecule fluctuation?

We start with the **Langevin Equation**:

$m\frac{d\vec{v}}{dt} = -b\vec{v} + \vec{f}(t)$

From there we can show that the **MSD** is (here he is giving us what it should look like, and he asks us to derive it in the homework):

$\langle \, r^2(t) - r^2(0) \, \rangle = 6k_BT \frac{\tau}{m}[t - \tau(1 - e^{\frac{-t}{\tau}})]$

Why do we mean by evolving?
Phase separation, things are changing...
How the properties are changing along this change...

**Again**, he is giving the answer and we will have to derive it:

The particle has two types of motion:

- **Balistic Motion**: $\langle r^2(t) - r^2(0) \rangle = \langle v^2 \rangle t^2 \\$
We want to do at a time scale that we do not worry about the Balistic Motion

- **Diffusive Motion**: $\langle r^2(t) - r^2(0) \rangle = \frac{6\,k_{B}T}{b}t \\$

This is what we are really interested in. It evolves linearly with time.

If I'm interested at the **Mean Square Displacement** and I assume that the initial position is at the origin (zero), then we can simplify this equation to:

$\langle r^2(t) \rangle = \frac{6\,k_{B}T}{b}t \\$

OR

$\langle r^2(t) \rangle = 6Dt$ , where $D = \frac{k_{B}T}{b}$

- **Fluctuation**: $\langle r^2(t) \rangle$
- Friction/Dissipation Factor: $D = \frac{k_{B}T}{b}$

We are using the symbol **r** to denote we are doing everything in 3 dimensions — 3D.

We can also write the same thing in a different way: $\langle \Delta r^2(t) \rangle = 2dDt \\$

Where **d** is the dimensionality of the situation:

- 1 D: d = 1
- 2 D: d = 2
- 3 D: d = 3

Examples:

- If we have an impurity which is diffusing along a thin film... that should be a **2D problem**.
- If we have an impurity diffusion within a grain boundary... although it is a 3D situation, normally a grain boundary is a 1D movement, so it is a **1D problem**.

This assignment of dimensionality is a tricky task, and we have to figure out the **correct equation to evaluate the motion**.

So, here we have the three ways to write the same thing:

$\langle r^2(t) - r^2(0) \rangle = \frac{6\,k_{B}T}{b}t \\$

$\langle r^2(t) \rangle = \frac{6\,k_{B}T}{b}t \\$

$\langle \Delta r^2(t) \rangle = \frac{6\,k_{B}T}{b}t \\$

There is a classical expression that come about, which is the **Diffusivity of a Sphere**:

$D = \frac{k_{B}T}{6 \pi \eta R} \\$

Which is the **Stokes-Einstein Equation**.

This calculation is being done everywhere we have a kind of coating.

Measuring Diffusion using Video Microscopy (**paper is on canvas, for homework**):

$R \sim 0.498 \mu m \\$

The diameter is about a micron. The plot is **MSD** vs **different time when you are measuring**.

The answer is gonna be: 

$\langle \Delta r^2(\tau) \rangle = 2dD\tau \\$
So that the slope is gonna be $\sim 4D$, from where we can get the diffusion constant:
$D = 0.46 \pm 0.01 \mu \frac{m^2}{s} \\$

Dissipation is not a good thing, but without dissipation we cannot have fluctuation.

It is the causality relation.

**If we take out dissipation, the fluctuation will die away.**

Dissipation is the origin of Fluctuation, however if we have larger dissipation we will have smaller fluctuation. But temperature will always keep things fluctuating.

$\frac{6k_{B}T}{b} = \int_{-\infty}^\infty \vec{v}(0) \cdot \vec{v}(t) dt \\$
