# Diffusion and Nucleation & Growth

- Mechanical source of deformation $\rightarrow \sigma \Omega$ (**free energy**) $\rightarrow$ **creep**

- Interfacial area (**incommensurate bonds**) $\rightarrow \frac{\gamma}{r}\Omega \rightarrow$ **smothing of interface**

Phase Transformation
- **Oswald Ripening**
- **Supercooling**
- **Superheating** $\rightarrow$ Premelting

Consider 2 particles in **continuous solid or liquid matrix**
- $r_1 < r_2$
    - $r_1$ is gonna shrink due to the higher pressure
    - $P_1 = \frac{2\gamma}{r_1}$
    - $P_2 = \frac{2\gamma}{r_2}$
        - Sets up **differential pressure**
        
Atoms want to move from **1** to **2**
- First, atoms need to **dissolve into continuous matrix** (dissolution is the **controlling parameter**, not vacancy generation)
    - **Long-range diffusion**

- $N_1 = e^{-(Q + \frac{2\gamma \Omega}{r_1})/K_BT} = N_o e^{-\frac{2\gamma \Omega}{r_1 K_BT}}$
- $N_2 = e^{-(Q + \frac{2\gamma \Omega}{r_2})/K_BT} = N_o e^{-\frac{2\gamma \Omega}{r_2 K_BT}}$

By **Taylor Expansion**
- $\Delta N_{1-2} = -\frac{2\Omega N_o \gamma}{K_BT}(\frac{1}{r_1} + \frac{1}{r_2})$
    - $(\frac{1}{r_1} + \frac{1}{r_2}) \approx \frac{2\langle r\rangle}{\langle r^2 \rangle} = \frac{2}{\langle r\rangle}$
    
For the Flux
- $\Delta N_{1-2} \approx -\frac{4\Omega N_o \gamma}{\langle r\rangle K_BT}$
- $ J_{1-2} = - \tilde D \frac{\Delta N_{1-2}}{\langle r\rangle} = \frac{\tilde D 4\Omega N_o \gamma}{\langle r\rangle^2 K_BT}$
    - $\Delta x \approx \langle r\rangle \rightarrow$ the particles are **reasonably close to each other**
    
**Manipulation** to make the **volume** appears in the right hand side
- $ J_{1-2} \frac{1}{\langle r\rangle} = \frac{4 \tilde D \Omega N_o \gamma}{\langle r\rangle^3 K_BT}$
- $\frac{\Delta V}{V} = \frac{4 \tilde D \Omega^2 N_o \gamma}{\langle r\rangle^3 K_BT} \Delta t$

Then:
- $\frac{\Delta \langle r\rangle }{\langle r\rangle} \propto \frac{4 \tilde D \Omega^2 N_o \gamma}{\langle r\rangle^3 K_BT} \Delta t$
- $\langle r\rangle^2 d\langle r\rangle \propto \frac{4 \tilde D \Omega^2 N_o \gamma}{K_BT} dt$

If we integrate:
- $\langle r\rangle^3 - \langle r_o\rangle^3 = Kt \Rightarrow \langle r\rangle \approx t^{\frac{1}{3}}$
    - **Oswald Ripening** $\rightarrow$ relationship of growth is important to know
    
## Grain Growth

**Grain Boundary** $\equiv$ **Interface**
- GB area $\downarrow$ then **free energy** $\downarrow$
- GB motion favored
- Some grains grow, and others disappear
- Grain size $\uparrow$ but $N_{grain} \downarrow$

Grain Growth $\rightarrow$ atoms diffuse across GB $\rightarrow$ **short-range diffusion**

Oswald Ripening
- Diffusion length $\propto \langle r \rangle$
- Over time $\rightarrow$ diffusion length $\uparrow$

**FINAL EXAM**: we should be able to find out that:
- $\langle r \rangle^2 - \langle r_o \rangle^2 = constant \cdot \gamma t M$
    - $M$ is the GB **Mobility**
  
## Kinetics of Phase Transformation

**Crystallization** is the **opposite of Melting**

**Crystallization**
- Liquid (disordered) $\rightarrow$ solid (ordered)
- They have **different densities**
- We have to worry about the **solid-liquid interface**
    - Surface **free energy** $\propto \gamma$
    - Energy barrier to form solid crystalline particle in a liquid (if barrier is too large, then no solid nuclei and it will not follow standard crystallization)
        - Liquid can exist **even when** solid is energeticaly favored (it can reach supercooled states)
        
**Crystallization** to form a solid of volume $V$ and surface area $A$
- $\Delta G = V \Delta G_V + V \Delta G_s + A\gamma$
    - $\Delta G_V < 0$ if **thermodynamicaly favored**
    - $\Delta G_s > 0 \rightarrow$ Is the **strain free energy** if solid phase has different **density** than the liquid phase
    - $A\gamma \rightarrow$ **Interfacial Energy**
        - $\gamma \rightarrow$ we always take it as **isotropic** (nuclei shapes are spherical $\rightarrow$ radius $r$)
        
Assume:
- $P = $ constant $\rightarrow$ liquid will flow to compensate for density difference
    - $\Delta G_s \rightarrow 0$
    - Note: constant volume $\rightarrow \Delta G_s$ is finite
    
**Free Energy of Transformation**
- $\Delta G_V = G_S - G_L$

**Nucleation Equation**
- $\Delta G = \frac{4}{3}\pi r^3 \Delta G_V + 4\pi r^2 \gamma$
    - (volume free energy) + (interfacial free energy)
  
If
- $r < r^* \rightarrow$ **interfacial free energy dominates**
    - particle size $\uparrow$ then **free energy $\uparrow$
        - **PROHIBITED**: solid particle melt away
- $r > r^* \rightarrow$ **volume free energy dominates**
    - particle size $\uparrow$ then **free energy $\downarrow$
        - **FAVORED**: **solid particles grow**
        
So, at $r^*$
- **Interface** free energy $=$ **Phase Transformation** free energy

## Determination of $r^*$

- $\frac{d\Delta G}{dr}|_{r=r^*} = 0 \Rightarrow [4\pi r^2 \Delta G_V + 8\pi r \gamma] = 0$
- $r^* = -\frac{2\gamma}{\Delta G_V}$
    - Laplace Pressure
    - Gibbs-Thompson
    
By plugging $r^*$ into the equation:
- $\Delta G^* = \frac{16 \pi \gamma^3}{3 \Delta G_V^2}$

**Undercooling**
- $\Delta T = (T - T_m)$
- $\Delta G_V = \frac{H_f \Delta T}{T_m}$
    - $H_f \equiv$ enthalpy = latent heat of melting/freeze
    
Then
- $r^* = \frac{2 \gamma T_m}{\Delta H_f \Delta T}$
- $\Delta G^* = \frac{16 \pi \gamma^3 T_m^2}{3 \Delta H_f^2 \Delta T^2}$

## Nucleation Rate

**Nuclei** (clusters) become **critical nuclei** if one atom jumps into the nuclei
- $N_o \equiv $ # of nuclei
- $\Delta G^* \equiv $ energy cost to form critical nuclei

Then
- $N^* = N_o e^{-\frac{\Delta G^*}{K_BT}}$

Say
- $\alpha \equiv a_o \equiv $ **atom radius, which is the R.W. Size**
- $\Gamma \equiv \frac{2D}{\alpha^2}$ **jump frequency**

And
- $N_s = \frac{4\pi (r^*)^3\alpha}{\Omega} \equiv$ # of atoms within $1$ **jump dinstance**
    - $\Omega = a_o^3$
    
Then, the **critical rate of nucleation**
- $\dot N^*  = N^* \Gamma N_s$

## Homogeneous Nucleation

**Homogeneous Nucleation Rate**
- $\dot N^*  = N^* \Gamma N_s$

## Heterogeneous Nucleation

Here the **interfacial area is significantly smaller**
- Total liquid-solid interface is smaller
- Energy is the same

Then
- We need an **spherical cap instead of a whole sphere** to start nucleation (crystallization
- So, much smaller nuclei reach critical nucleus size
- Crystallization is faster
